export const ROOT_LOGGER = "ROOT_LOGGER";
export const NESTJS_BUNYAN_ROOT_LOGGER = ROOT_LOGGER;

export const LOGGER = "LOGGER";
export const NESTJS_BUNYAN_LOGGER = LOGGER;

export const LOGGING_OPTIONS = "LOGGING_OPTIONS";
export const NESTJS_BUNYAN_LOGGING_OPTIONS = LOGGING_OPTIONS;
